### ISSUE TITLE
[Enhancement] criar opção de chat para video e chat/text

### ISSUE THREAD

**Issue by brunooomelo** [pagarme/the-office#27]
## Descrição
Ao criar uma sala (gerenciar), ter uma opção de sala de chat ( sem vídeo ) e ao invés de abrir o vídeo, iria ter um chat.

### Exemplo:
![image](https://user-images.githubusercontent.com/12174318/61823502-51791b80-ae32-11e9-864a-f4f47b68b6e3.png)

### Destaques
A issue #15  seria super necessário

**Comment by lucianopf** [comment]
Perspicaz!! 
Acho válido sim mano! Como é uma flag booleana eu tava mais pensando tipo um checkbox tipo de `sem vídeo` 🤔 

Acha que faz sentido?

**Comment by brunooomelo** [comment]
sim, mas pode ficar um pouco confuso, pois o usuário pode pensar "quero sem vídeo, só áudio", então com a opção de chat, fica explicito que é vídeo ou chat (texto).

**Comment by lucianopf** [comment]
Então, aí que mora o problema hahaha, não existe o conceito de Chat sem o componente do Meet(Jitsi), na verdade o sem "Meet" é só um sistema de presença onde a pessoa diz que ta "ocupada" com alguma coisa e portanto indisponível
